# Files are "installed" as hard links.
# Directories are "installed" as symlinks.
entries:
  dir_colors: .dir_colors
  gitconfig: .gitconfig
  gitignore_global: .gitignore_global
  fish: .config/fish
  i3: .config/i3
  tmux: .config/tmux
  vim-autoload: .vim/autoload
  vim-bin: .vim/bin
  vim-colors: .vim/colors
  vimrc: .vimrc
  xinitrc: .xinitrc
  Xresources: .Xresources
  xserverrc: .xserverrc

